# -*- coding: utf-8 -*-
"""praktik 5 algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lub-ppjgfqUelsVXsdcJo2ncq55C2fxL
"""

#Latihan 1
nilai_huruf = {'A': 4.00,'A-': 3.75,'B+': 3.50,'B': 3.00,'B-': 2.75,'C+': 2.50,'C': 2.00,'C-': 1.75,'D': 1.50,'E': 1.25 }

jumlah_matkul = int(input("Masukkan jumlah mata kuliah: "))

nilai = []
for i in range(jumlah_matkul):
    huruf = input(f"Masukkan nilai huruf untuk mata pelajaran ke-{i+1}: ")
    nilai.append(huruf)

total_poin = 0
for huruf in nilai:
    total_poin += nilai_huruf.get(huruf, 0)  # Mengonversi huruf ke nilai

rata_rata = total_poin / jumlah_matkul


print(f"Rata-rata nilai adalah: {rata_rata:.2f}")

#Latihan 2
total_harga = 0
while True:
    umur = input("Masukkan umur pengunjung (atau ketik 'selesai' untuk menghitung total): ")
    if umur.lower() == 'selesai':
        break
    umur = int(umur)

    if umur <= 2:
        harga_tiket = 0  # Gratis untuk umur 2 tahun ke bawah
    elif 3 <= umur <= 12:
        harga_tiket = 14  # 14 dollar untuk umur 3 hingga 12 tahun
    elif umur >= 65:
        harga_tiket = 18  # 18 dollar untuk umur 65 tahun ke atas
    else:
        harga_tiket = 23  # Harga normal 23 dollar

    total_harga += harga_tiket  # Menambahkan harga tiket ke total

print(f"Total harga tiket: {total_harga} dollar")

uang_dibayarkan = float(input("Masukkan jumlah uang yang dibayarkan: "))

if uang_dibayarkan > total_harga:
    kembalian = uang_dibayarkan - total_harga
    print(f"Kembalian: {kembalian:.2f} dollar")
elif uang_dibayarkan == total_harga:
    print("Uang pas, tidak ada kembalian.")
else:
    kekurangan = total_harga - uang_dibayarkan
    print(f"Uang yang dibayarkan kurang: {kekurangan:.2f} dollar")